{
 "title": "Actor System Specific Logs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Actor System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", job=\"asteroids\"} | json | attributes_SourceContext = `Akka.Actor.ActorSystem` | line_format `{{.body}}` | pattern `[<actor_level>][<actor_timestamp>][<actor_thread>][<actor_path>] <actor_body>` | line_format ` {{.actor_body}} {{.actor_path }}`"
    }
   ]
  },
  {
   "title": "Actor System Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", job=\"asteroids\", level=\"ERROR\"} | json | attributes_SourceContext = `Akka.Actor.ActorSystem` | line_format `{{.body}}` | pattern `[<actor_level>][<actor_timestamp>][<actor_thread>][<actor_path>] <actor_body>` | line_format ` {{.actor_body}} {{.actor_path }}`"
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"asteroids\"} | json | body =~ `(Dead|Unhandled) letter: Sender .*Message: .*` | line_format `{{ .body | replace \"{Sender}\" .attributes_Sender | replace \"{Recipient}\" .attributes_Recipient | replace \"{Message}\" .attributes_Message }}`"
    }
   ]
  }
 ]
}