{
 "title": "Asteroid Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Running Lobbies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(asteroids_lobbies_created_total) - sum(asteroids_lobbies_destroyed_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players In Game",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asteroids_players_in_lobby_Number_of_players_in_lobby",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game Tick Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(asteroids_game_ticks_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}