include:
  - ./ops/dev/observability/docker-compose.yml
  - ./src/compose.raft.yaml

x-dotnet_sync: &dotnet_sync
  develop:
    watch:
      - action: sync
        path: ./src/Asteroids/
        target: ./src/Asteroids/

x-client_config: &client_config
  build:
    context: ./src/
    dockerfile: ./Asteroids/Asteroids.Client/Dockerfile
    target: development
  environment:
    ASPNETCORE_ENVIRONMENT: Development
    ASPNETCORE_URLS: http://+:8080
    ObservabilityOptions__CollectorUrl: http://collector:4317
    ObservabilityOptions__ServiceName: asteroids-client
    TZ: America/Denver
  <<: *dotnet_sync

x-asteroids_system_base: &asteroids_system_base
  build:
    context: ./src/
    dockerfile: ./Asteroids/Asteroids.AsteroidSystem/Dockerfile
    target: development
  <<: *dotnet_sync

x-asteroids_system_env: &asteroids_system_env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ObservabilityOptions__ServiceName: asteroids-system
  ApiOptions__AkkaSeeds: "akka.tcp://MyAsteroidSystem@lighthouse:4053"
  ApiOptions__RaftStorageUrl: "http://storage-api:8080/gateway"
  TZ: America/Denver

services:
  nginx:
    build:
      context: ./ops/dev/
      dockerfile: nginx.Dockerfile
    ports:
      - "3001:80"
    develop:
      watch:
        - action: sync+restart
          path: ./ops/dev/nginx.conf
          target: /etc/nginx/conf.d/default.conf

  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - "9110:9110"
      - "4053:4053"
    environment:
      ACTORSYSTEM: "MyAsteroidSystem"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://MyAsteroidSystem@lighthouse:4053"
    restart: unless-stopped

  asteroids-system:
    container_name: asteroids-system
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: SignalR # comma separated list of roles
      ApiOptions__AkkaHostname: asteroids-system

  asteroids-node1:
    container_name: asteroids-node1
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: Lobbies # comma separated list of roles
      ApiOptions__AkkaHostname: asteroids-node1

  asteroids-node2:
    container_name: asteroids-node2
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: Lobbies # comma separated list of roles
      ApiOptions__AkkaHostname: asteroids-node2

  asteroids-client1:
    container_name: asteroids-client-1
    <<: *client_config

  asteroids-client2:
    container_name: asteroids-client-2
    <<: *client_config
