include:
  - compose.telemetry.yml

services:
  swag:
    container_name: w-asteroids-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=disasteroids.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:4321:443
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --fail https://disasteroids.duckdns.org:4321 || exit 1
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s

  asteroids-system:
    container_name: w-asteroids-system
    build:
      context: ../../src/
      dockerfile: ./Asteroids/Asteroids.AsteroidSystem/Dockerfile
      target: final
    environment:
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__CollectorUrl: http://collector:4317
      ObservabilityOptions__ServiceName: asteroids-system
      TZ: America/Denver

  asteroids-client:
    container_name: w-asteroids-client
    build:
      context: ../../src/
      dockerfile: ./Asteroids/Asteroids.Client/Dockerfile
      target: final
    environment:
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__CollectorUrl: http://collector:4317
      ObservabilityOptions__ServiceName: asteroids-client
      TZ: America/Denver

  # https://medium.com/@saklani1408/configuring-healthcheck-in-docker-compose-3fa6439ee280
  autoheal:
    container_name: w-autoheal
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: w-asteroids-network
