x-node_base: &node_base
  build:
    context: ../../src/Raft/
    dockerfile: ./Raft.Node/Dockerfile
    target: final
  restart: unless-stopped

x-node-environment: &node-environment
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ApiOptions__NodeCount: 3
  ApiOptions__NodeServiceName: node
  ApiOptions__NodeServicePort: 8080
  ApiOptions__LogMessageIntervalSeconds: 10
  TZ: America/Denver

services:
  storage-api:
    container_name: w-raft-gateway
    build:
      context: ../../src/Raft/
      dockerfile: ./Raft.Gateway/Dockerfile
      target: final
    environment:
      ApiOptions__NodeCount: 3
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    profiles:
      - manager
    restart: unless-stopped

  node1:
    container_name: w-raft-node1
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 1
      ObservabilityOptions__ServiceName: Node1
    profiles:
      - manager

  node2:
    container_name: w-raft-node2
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 2
      ObservabilityOptions__ServiceName: Node2
    profiles:
      - manager

  node3:
    container_name: w-raft-node3
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 3
      ObservabilityOptions__ServiceName: Node3
    profiles:
      - worker
