include:
  - compose.telemetry.yml
  - compose.raft.yml

x-asteroids_client_config: &asteroids_client_config
  build:
    context: ../../src/
    dockerfile: ./Asteroids/Asteroids.Client/Dockerfile
    target: final
  environment:
    ASPNETCORE_URLS: http://+:8080
    ObservabilityOptions__CollectorUrl: http://collector:4317
    ObservabilityOptions__ServiceName: asteroids
    TZ: America/Denver

x-asteroids_system_base: &asteroids_system_base
  build:
    context: ../../src/
    dockerfile: ./Asteroids/Asteroids.AsteroidSystem/Dockerfile
    target: final

x-asteroids_system_env: &asteroids_system_env
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ObservabilityOptions__ServiceName: asteroids
  ApiOptions__AkkaSeeds: "akka.tcp://MyAsteroidSystem@lighthouse:4053"
  ApiOptions__RaftStorageUrl: "http://storage-api:8080/gateway"
  TZ: America/Denver

services:
  swag:
    container_name: w-asteroids-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=disasteroids.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:4321:443
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --fail https://disasteroids.duckdns.org:4321 || exit 1
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s

  lighthouse:
    image: petabridge/lighthouse:latest
    container_name: w-lighthouse
    hostname: lighthouse
    environment:
      ACTORSYSTEM: "MyAsteroidSystem"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://MyAsteroidSystem@lighthouse:4053"

  asteroids-system:
    container_name: w-asteroids-system
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: SignalR
      ApiOptions__AkkaHostname: asteroids-system

  asteroids-node1:
    container_name: w-asteroids-node-1
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: Lobbies
      ApiOptions__AkkaHostname: asteroids-node1

  asteroids-node2:
    container_name: w-asteroids-node-2
    <<: *asteroids_system_base
    environment:
      <<: *asteroids_system_env
      ApiOptions__AkkaRoles: Lobbies
      ApiOptions__AkkaHostname: asteroids-node2

  asteroids-client1:
    container_name: w-asteroids-client-1
    <<: *asteroids_client_config

  asteroids-client2:
    container_name: w-asteroids-client-2
    <<: *asteroids_client_config

  # https://medium.com/@saklani1408/configuring-healthcheck-in-docker-compose-3fa6439ee280
  autoheal:
    container_name: w-autoheal
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: w-asteroids-network
