name: Deploy

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/format.yml

  tests:
    needs: format
    uses: ./.github/workflows/tests.yml

  deploy-application:
    needs: tests
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: redeploy application
        run: |
          cd ops/prod
          docker compose pull
          docker compose down
          docker compose up -d --build

  # ensure-network:
  #   needs: deploy-application
  #   runs-on: [self-hosted, alex-office4]

  #   steps:
  #     - name: run container to ensure network
  #       run: |
  #         docker run -d --rm --name w-network-opener --network w-overlay alpine sleep 30

  # deploy-other-node:
  #   needs: ensure-network
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v3

  #     - name: redeploy application
  #       run: |
  #         cd ops/prod
  #         docker compose pull
  #         docker compose --profile worker up -d --build
