name: Dotnet Format

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dotnet-format:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: |
          cd src
          docker build -t asteroids_format .
          docker run -i --rm asteroids_format dotnet format --verify-no-changes --verbosity diagnostic --no-restore