name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    uses: ./.github/workflows/format.yml

  tests:
    needs: format
    uses: ./.github/workflows/tests.yml
