name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          cd src/
          docker build -t asteroid_tests .
          docker run -i --rm asteroid_tests dotnet test
